platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11-alpine

run:
  path: src/ci/scripts/build-client.sh

inputs:
  - {name: src, optional: false }
  - { name: version, optional: false }
outputs: [ { name: output }]

params:
  os: linux
  arch: amd64
  version_file: version/number
